# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ia2017/hpc-exercises/hpc-coursework-new

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ia2017/hpc-exercises/hpc-coursework-new

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ia2017/hpc-exercises/hpc-coursework-new/CMakeFiles /home/ia2017/hpc-exercises/hpc-coursework-new/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ia2017/hpc-exercises/hpc-coursework-new/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runliddrivencavity

# Build rule for target.
runliddrivencavity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runliddrivencavity
.PHONY : runliddrivencavity

# fast build rule for target.
runliddrivencavity/fast:
	$(MAKE) -f CMakeFiles/runliddrivencavity.dir/build.make CMakeFiles/runliddrivencavity.dir/build
.PHONY : runliddrivencavity/fast

LidDrivenCavity.o: LidDrivenCavity.cpp.o

.PHONY : LidDrivenCavity.o

# target to build an object file
LidDrivenCavity.cpp.o:
	$(MAKE) -f CMakeFiles/runliddrivencavity.dir/build.make CMakeFiles/runliddrivencavity.dir/LidDrivenCavity.cpp.o
.PHONY : LidDrivenCavity.cpp.o

LidDrivenCavity.i: LidDrivenCavity.cpp.i

.PHONY : LidDrivenCavity.i

# target to preprocess a source file
LidDrivenCavity.cpp.i:
	$(MAKE) -f CMakeFiles/runliddrivencavity.dir/build.make CMakeFiles/runliddrivencavity.dir/LidDrivenCavity.cpp.i
.PHONY : LidDrivenCavity.cpp.i

LidDrivenCavity.s: LidDrivenCavity.cpp.s

.PHONY : LidDrivenCavity.s

# target to generate assembly for a file
LidDrivenCavity.cpp.s:
	$(MAKE) -f CMakeFiles/runliddrivencavity.dir/build.make CMakeFiles/runliddrivencavity.dir/LidDrivenCavity.cpp.s
.PHONY : LidDrivenCavity.cpp.s

PoissonSolver.o: PoissonSolver.cpp.o

.PHONY : PoissonSolver.o

# target to build an object file
PoissonSolver.cpp.o:
	$(MAKE) -f CMakeFiles/runliddrivencavity.dir/build.make CMakeFiles/runliddrivencavity.dir/PoissonSolver.cpp.o
.PHONY : PoissonSolver.cpp.o

PoissonSolver.i: PoissonSolver.cpp.i

.PHONY : PoissonSolver.i

# target to preprocess a source file
PoissonSolver.cpp.i:
	$(MAKE) -f CMakeFiles/runliddrivencavity.dir/build.make CMakeFiles/runliddrivencavity.dir/PoissonSolver.cpp.i
.PHONY : PoissonSolver.cpp.i

PoissonSolver.s: PoissonSolver.cpp.s

.PHONY : PoissonSolver.s

# target to generate assembly for a file
PoissonSolver.cpp.s:
	$(MAKE) -f CMakeFiles/runliddrivencavity.dir/build.make CMakeFiles/runliddrivencavity.dir/PoissonSolver.cpp.s
.PHONY : PoissonSolver.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/runliddrivencavity.dir/build.make CMakeFiles/runliddrivencavity.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/runliddrivencavity.dir/build.make CMakeFiles/runliddrivencavity.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/runliddrivencavity.dir/build.make CMakeFiles/runliddrivencavity.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... runliddrivencavity"
	@echo "... edit_cache"
	@echo "... LidDrivenCavity.o"
	@echo "... LidDrivenCavity.i"
	@echo "... LidDrivenCavity.s"
	@echo "... PoissonSolver.o"
	@echo "... PoissonSolver.i"
	@echo "... PoissonSolver.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

